### ISSUE TITLE
UnspecifiedHeightError, already specified

### ISSUE THREAD

**Issue by AlexUrielRamirez** [gbenroscience/layman#1]
Hi!

im trying to make simple image to constraint ss & tt but im getting the "UnspecifiedHeightError" exception, here is my code

`<img id="splash_image" src="logo.png" data-const="w:100px, h:150px, ss:parent, tt: parent">`

am i missing something?...

thanks in advance for the help.

**Comment by gbenroscience** [comment]
Hi @AlexUrielRamirez, thanks for using **layman**.
I have to apologize for the mixup. The syntax for the constraints changed slightly as the library evolved.
I just updated the README to reflect this.
So your syntax now will be:
```HTML
<img id="splash_image" src="logo.png" data-const="w:100px; h:150px; ss:parent; tt: parent;">
```

Thanks.

**Comment by AlexUrielRamirez** [comment]
It works now, thanks my man.
